### ISSUE TITLE
Nice progress

### ISSUE THREAD

**Issue by i-am-the-slime** [hendrikniemann/purescript-graphql#11]
> If you want to give feedback please open an issue

Congratulations on the latest improvements!

**Comment by hendrikniemann** [comment]
Thanks a lot! Unfortunately, there are still some huge blockers. Mainly around recursive types (I want to have a `Lazy` implementation but that's really hard) and Introspection is also huge (because you need it for all the tooling).

One thing that I would really like to see is something like [facebook/Haxl](https://github.com/facebook/Haxl) for PureScript. It is the cleanest way to solve the n+1 problem. But everytime I make an attempt at creating something similar I make no progress at all 😞
