### ISSUE TITLE
Use `simple-json` for JSON

### ISSUE THREAD

**Issue by i-am-the-slime** [hendrikniemann/purescript-graphql#9]
https://github.com/taojang/purescript-graphql

Is doing this. Generally it's `simple`r. Do you have a specific reason to use Argonaut?

**Comment by hendrikniemann** [comment]
In version 1 of this library it doesn't really matter because I simply need a type to represent foreign values. When I started this I wasn't really aware what is in the ecosystem. It sucks a bit to have to depend on a JSON library or at least to expose it to the user of the library.

In version 2 though contructing JSONs is an important part of the library because it is 100% written in PureScript. I don't think that [combinator functionalities](https://pursuit.purescript.org/packages/purescript-argonaut-codecs/6.0.2/docs/Data.Argonaut.Encode.Combinators) is available in `simple-json`.

To be honest I think that version 1 of purescript-graphql is a nice proof of concept but not really dogmatic and performant (see #7). I think I am really close to a breakthrough with v2 but somehow I have lost my stamina. It's not really a beginner project and that's unfortunately what I am. Let me know if you are interested in the library in general. For my company I have unfortunately chosen TypeScript because the PS server ecosystem is pretty much non-existent and the TS ecosystem is unbeatable. So I don't really have a use for the library myself besides the mental challenge.

**Comment by i-am-the-slime** [comment]
Purescript on the server-side is a dream come true, we use it here to great success. We are also using your library. 
Are you interested in some collaboration?
Since you're in Berlin, we could even meet up at some point and hack on it if you're interested (I can promise at least one more colleague). That can be a lot more fun together.

**Comment by hendrikniemann** [comment]
Yes, would love to meet and discuss what is in for version two. Just you opening this issue got me working on it again ❤️ Hit me up on FP slack with the same name as my Github.
And check out my [example for v2](https://github.com/hendrikniemann/purescript-graphql/blob/master/test/Execution.purs#L23-L98).

For this issue though, I could create a legacy branch, make the change you proposed by copying taojang's code and add a minor version tag. This should be enough for Spago. You are probably not using bower, right?

**Comment by i-am-the-slime** [comment]
@hendrikniemann That sounds pretty cool. We are using bower. Right now we're pointing at @taojang's repository. We have a problem that optional types do not work. It looks like we're behind. Is everything on the master branch still v1?

**Comment by hendrikniemann** [comment]
To wrap this up: I see how it can be useful to use foreign for exposing the result and I would definitely consider `Foreign` over Agonaut's `Json` in version 2. But I will not make the change to version one here for several reasons:

- Changing this now would be a breaking change. There are probably not that many users of this library but why fix what isn't broken?
- You are probably not doing much with the output other than calling _stringify_ on it. There is no `Foreign -> String` in `purescript-simple-json`. So this adds some inconvenience. 
- If you want to use simple JSON with this library this should not be a big deal. An `unsafeCoerce` should do the job. Thanks to dead code elimination Argonaut will not blow up the dependencies when it matters.
- For all other cases you could fork the library

I hope a version 2 release is somewhere on the horizon. It's still lacking essential features but v1 is missing some stuff as well.
